version: 2
jobs:
  build-and-test:
    macos:
      xcode: 11.0.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/Example/fastlane/test_output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: mkdir $FL_OUTPUT_DIR
      - run: bundle install
      - run:
          name: Fastlane
          command: cd Example; bundle exec fastlane $FASTLANE_LANE; cd --
      - run:
          command: cp $FL_OUTPUT_DIR/report.junit $FL_OUTPUT_DIR/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/project/Example/fastlane
      - store_test_results:
          path: /Users/distiller/project/Example/fastlane/test_output

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test