version: 2
jobs:
  build-and-test-pods:
    macos:
      xcode: 13.4.1
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: brew install mint
      - run: mint bootstrap --link
      - run: mint run -m Mintfile swiftlint version
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane ios test_pod
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  build-and-test-spm:
    macos:
      xcode: 13.4.1
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: brew install mint
      - run: mint bootstrap --link
      - run: mint run -m Mintfile swiftlint version
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane ios test_spm
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test-pods
      - build-and-test-spm
