version: 2.1

orbs:
  ruby: circleci/ruby@2.3.0

jobs:
  build-and-test:
    macos:
      xcode: 16.0.0
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: ruby -v
      - ruby/install-deps
      - run: brew bundle
      - run: bundle exec fastlane ios lint
      - run: bundle exec fastlane ios test
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  danger:
    macos:
      xcode: 16.0.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: brew tap danger/tap
      - run: brew install danger/tap/danger-swift
      - run:
          name: Danger
          command: danger-swift ci

workflows:
  version: 2.1
  build-test-adhoc:
    jobs:
      - build-and-test
      - danger
