# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test_pod do
    cocoapods(podfile: './Example/PodApp/Podfile')
    scan(
      workspace: "./Example/PodApp/SplitScreenScanner.xcworkspace", 
      scheme: "SplitScreenScanner-Example", 
      device: "iPhone 8", 
      clean: true
      )
  end
  lane :test_spm do
    scan(
      workspace: './Example/SPMApp/SplitScreenScanner.xcworkspace',
      scheme: "SplitScreenScannerExample",
      device: "iPhone 8",
      clean: true
    )
  end
end
